import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [todos, setTodos] = useState([]) // State to store the todos

  const addTodo = (todo) => {
    setTodos([...todos, todo]) // Add a new todo to the list
  }

  const removeTodo = (index) => {
    const updatedTodos = [...todos]
    updatedTodos.splice(index, 1)
    setTodos(updatedTodos)
  }

  return (
    <>
      <Head>
        <title>Success!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Todo List</h1>
        <form onSubmit={(e) => {
          e.preventDefault()
          const todo = e.target.todo.value
          addTodo(todo)
          e.target.todo.value = ''
        }}>
          <input type="text" name="todo" placeholder="Enter a todo" />
          <button type="submit">Add Todo</button>
        </form>
        <ul className='todo-list'>
          {todos.map((todo, index) => (
            <li className='todo-item' key={index}>
              {todo}
              <button onClick={() => removeTodo(index)}>X</button>
            </li>
          ))}
        </ul>
      </main>
    </>
  )
}
